### PR TITLE
Removed sampleRate from the audioContext initialization

### PR DESCRIPTION
**Pull request by ZhenyaPav**
The sample rate seems to be the cause of #9, removing it fixed the problem for me

### CODE REVIEW

**Comment by ZhenyaPav** [comment]
Might need further testing - I wasn't able to get speech recognition to work with this fix on my laptop and phone (I launch SillyTavern on my PC and connect on the LAN)

**Comment by yar3333** [comment]
I test this on fresh Firefox - work good (koboldcpp). 

Chrome not work with koboldcpp before fix and after fix too: no errors, always output "you" or ".".

**Comment by yar3333** [comment]
@Cohee1207 May we do something to become this pull request to ready-to-merge state? Is Firefox support important or you focused to support Chrome only?

**Comment by Cohee1207** [comment]
This has to be a conditional. If Firefox - don't set the sample rate. We have quite a few `isFirefox` statements through the code base.

**Comment by Cohee1207** [comment]
Superseded by #16

**Pull request closed without merging**
